# Generated by Django 3.2.12 on 2023-07-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='accessories',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.Accessory'),
        ),
    ]
