# Generated by Django 3.2.12 on 2023-07-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='home',
            field=models.CharField(default='earth', max_length=100),
            preserve_default=False,
        ),
    ]
